import Header from "@/components/Home/Header";
import "./globals.css";
import { Inter, Rubik } from "next/font/google";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
  variable: "--font-rubik",
  weight: ["300", "400", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <main className="max-w-[1500px] overflow-x-hidden m-auto relative h-fit">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
